rooms_json = [
    {
        "classroomId": "1",
        "name": "NB111",
        "capacity": 300,
        "type": "lecture",
        "buildingId": "1",
        "floor": 0,
        "roomNumber": 1,
        "isWheelchairAccessible": True,
    },
    {
        "classroomId": "2",
        "name": "NB112",
        "capacity": 100,
        "type": "lecture",
        "buildingId": "1",
        "floor": 1,
        "roomNumber": 2,
        "isWheelchairAccessible": True,
    },
    {
        "classroomId": "3",
        "name": "NB113",
        "capacity": 100,
        "type": "lecture",
        "buildingId": "1",
        "floor": 1,
        "roomNumber": 3,
        "isWheelchairAccessible": True,
    },
    {
        "classroomId": "4",
        "name": "NB114",
        "capacity": 50,
        "type": "lab",
        "buildingId": "1",
        "floor": 2,
        "roomNumber": 4,
        "isWheelchairAccessible": False,
    },
    {
        "classroomId": "5",
        "name": "NB115",
        "capacity": 50,
        "type": "lab",
        "buildingId": "1",
        "floor": 2,
        "roomNumber": 5,
        "isWheelchairAccessible": False,
    },
]

teachers_json = [
    {
        "teacherId": "1",
        "name": "Abrham",
        "email": "abrham@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    },
    {
        "teacherId": "2",
        "name": "Natinael",
        "email": "natinael@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    },
    {
        "teacherId": "3",
        "name": "Nebiat",
        "email": "nebiat@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    },
    {
        "teacherId": "4",
        "name": "Amanuel",
        "email": "amanuel@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    },
    {
        "teacherId": "5",
        "name": "Tewodros",
        "email": "tewodros@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    },
    {
        "teacherId": "6",
        "name": "Yared",
        "email": "yared@gmail.com",
        "phone": "1234567890",
        "departmentId": "1",
    }
]

# Courses: intro to cs, intro to it, intro to ai, intro to networking, OS, intro to db, Machine Learning, Distributed Systems, Software Engineering 
# courses_json = [
#     {
#         "courseId": "1",
#         "name": "Intro To CS",
#         "description": "Intro To CS",
#         "ectsCredits": 2,
#         "department": "1",
#         "teacherId": "1",
#         "sessionTypes": ["lecture", "lab"],
#         "sessionsPerWeek": [2, 2],
#     },
#     {
#         "courseId": "2",
#         "name": "Intro to IT",
#         "description": "Intro to IT",
#         "ectsCredits": 4,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
#     {
#         "courseId": "3",
#         "name": "Intro to AI",
#         "description": "Intro to AI",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
#     {
#         "courseId": "4",
#         "name": "Intro to Networking",
#         "description": "Intro to Networking",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture", "lab"],
#         "sessionsPerWeek": [2, 2],
#     },
#     {
#         "courseId": "5",
#         "name": "Operating Systems",
#         "description": "Operating Systems",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "1",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
#     {
#         "courseId": "6",
#         "name": "Intro to DB",
#         "description": "Intro to DB",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
#     {
#         "courseId": "7",
#         "name": "Machine Learning",
#         "description": "Machine Learning",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },   
#     {
#         "courseId": "8",
#         "name": "Distributed Systems",
#         "description": "Distributed Systems",
#         "ectsCredits": 10,
#         "department": "1",
#         "teacherId": "2",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
#     {
#         "courseId": "9",
#         "name": "Software Engineering",
#         "description": "Software Engineering",
#         "ectsCredits": 3,
#         "department": "1",
#         "teacherId": "3",
#         "sessionTypes": ["lecture"],
#         "sessionsPerWeek": [2],
#     },
# ]

courses_json = [
    {
        "courseId": "1",
        "name": "elec",
        "description": "Fundamentals of Electrical Engineering",
        "ectsCredits": 5,
        "department": "1",
        "teacherId": "1",
        "sessionTypes": ["lecture", "lab"],
        "sessionsPerWeek": [1, 1],
    },
    {
        "courseId": "2",
        "name": "web",
        "description": "Modern Web Development",
        "ectsCredits": 5,
        "department": "1",
        "teacherId": "2",
        "sessionTypes": ["lecture", "lab"],
        "sessionsPerWeek": [1, 1],
    },
    {
        "courseId": "3",
        "name": "hci",
        "description": "Principles of HCI",
        "ectsCredits": 5,
        "department": "1",
        "teacherId": "3",
        "sessionTypes": ["lecture", "lab"],
        "sessionsPerWeek": [1, 1],
    },
    {
        "courseId": "4",
        "name": "se",
        "description": "Software Engineering Practices",
        "ectsCredits": 5,
        "department": "1",
        "teacherId": "4",
        "sessionTypes": ["lecture", "lab"],
        "sessionsPerWeek": [1, 1],
    },
    {
        "courseId": "5",
        "name": "comparch",
        "description": "Computer Architecture Fundamentals",
        "ectsCredits": 5,
        "department": "1",
        "teacherId": "5",
        "sessionTypes": ["lecture", "lab"],
        "sessionsPerWeek": [1, 1],
    },
]


class SampleData:
    def __init__(self):
        self.rooms = rooms_json
        self.teachers = teachers_json
        self.courses = courses_json