
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=securepassword123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  nestjs-app:
    build:
      context: ./core
      dockerfile: ../.docker/core.backend.dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://admin:securepassword123@rabbitmq:5672
      - NODE_ENV=development
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

  # python-service:
  #   build:
  #     context: ./python-service
  #     dockerfile: Dockerfile
  #   container_name: python-service
  #   environment:
  #     - RABBITMQ_URL=amqp://admin:securepassword123@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq
  #   # networks:
  #   #   - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data: