
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 dataparser.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db
    environment:
      - PYTHONUNBUFFERED=1

  # db:
    # image: sqlite:latest
    # volumes:
    #   - sqlite_data:/data
    # environment:
    #   - SQLITE_DATABASE=/data/db.sqlite3

volumes:
  sqlite_data:
